@startuml
Title Interrupts
state "PinInterrupt" as p{
    state "idle" as idle_pin
    state "ISR" as isr_pin
    isr_pin: Änderung der Laufrichtung
    isr_pin: Zurücksetzen der Interruptflag
    idle_pin --> isr_pin : Button S1 wird gedrückt\n
    
    isr_pin --> idle_pin : \nISR Ende
}
state "ADCInterrupt" as a{
    state "idle" as idle_adc
    state "ISR" as isr_adc
    isr_adc : ADC-Wert zu Timerperiode 
    idle_adc --> isr_adc : Sampeling zu ende\n
    isr_adc --> idle_adc : \nISR Ende
}

p -right[hidden]-> a
state "TimerInterrupt" as t{
    state "idle" as idle_t
    state "ISR" as isr_t
    isr_t : Wähle nächste LED aus
    idle_t --> isr_t : Timerüberlauf\n
    isr_t --> idle_t : \nISR Ende

}
state "UART-TX-Interrupt" as u{
    state "idle" as idle_u
    state "ISR" as isr_u
    isr_u : nächste uart Botschaft in TX FIFO Buffer
    idle_u --> isr_u : Platz in TX FIFO Buffer\n
    isr_u --> idle_u : \nISR Ende
    
}
t-right[hidden]->u
@enduml