@startuml
robust "Pegel" as p
concise "Bitwert" as w
p has 1,0

w is " "
Title Timing für LED-Bit
caption Zeit in ns ⟶
@-300
p is 0
@0
p is 1
w is "0"
@+300
p is 0
@+900
p is 1
w is "1"
@+600
p is 0
@+600
p is 1
w is " "
p@0 <-> @+300 : 300 ns
p@1200 <-> @+600 : 600 ns
w@0 <-> @+1200 : 1200 ns
w@1200 <-> @+1200 : 1200 ns
@enduml 